[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
)/
'''

[tool.isort]
line_length = 100
profile = "black"
filter_files = true

[tool.mypy]

[[tool.mypy.overrides]]
module = [
    "sympy",
    "dimod",
    "docplex",
    "pandas"
]
ignore_missing_imports = true



