name: Quality checks

on: [push]

jobs:
  run_quality_cheks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/checkout@v2
      - run: pip install pyenchant
      - name: Run quality checks
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "omniqubo"
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-mypy: true
          use-black: true
          use-isort: true
          extra-mypy-options: --ignore-missing-imports --namespace-packages
